"""Sub-agent responsible for reviewing and selecting the best email draft."""

from agents import Agent

from models import model_registry
from schemas import ReviewResult


review_instructions = """
You are the Quality Assurance Director for the email campaign.
Your job is to review multiple candidate email drafts and select the best one based on:
1. Relevance to the specific campaign goals.
2. Clarity and professional tone.
3. Effectiveness of the Call-To-Action (CTA).

You will be provided with the drafts generated by different sales agents.
Evaluate them carefully and return your structured decision identifying the winning draft.
""".strip()

review_agent = Agent(
    name="review_agent",
    instructions=review_instructions,
    model=model_registry["openai"],
    output_type=ReviewResult,
)
